################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/absolute.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/algorithm.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/alignment.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array_view.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array_wrapper.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/atomic.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_format_spec.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_string.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_string_stream.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/binary.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bip_buffer_spsc_atomic.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bit.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bit_stream.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bitset.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bloom_filter.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bresenham_line.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/buffer_descriptors.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/byte.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/byte_stream.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_service.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_timer.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_timer_atomic.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/char_traits.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/checksum.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/circular_buffer.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/combinations.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/compare.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/constant.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/container.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/correlation.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/covariance.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_a.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_arc.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_aug_ccitt.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_buypass.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_ccitt.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_cdma2000.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dds110.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dectr.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dectx.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dnp.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_en13757.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_genibus.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_kermit.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_maxim.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_mcrf4xx.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_modbus.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_profibus.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_riello.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_t10dif.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_teledisk.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_tms37157.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_usb.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_x25.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_xmodem.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_bzip2.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_c.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_d.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_jamcrc.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_mpeg2.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_posix.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_q.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_xfer.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc64_ecma.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_ccitt.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_cdma2000.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_darc.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_dvbs2.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_ebu.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_icode.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_itu.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_maxim.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_rohc.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_wcdma.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/cumulative_moving_average.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/cyclic_value.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/debounce.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/debug_count.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate_cpp03.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate_service.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/deque.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/endianness.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/enum_type.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/error_handler.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/exception.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/factorial.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fibonacci.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/file_error_numbers.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fixed_iterator.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fixed_sized_memory_block_allocator.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flags.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_map.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_multimap.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_multiset.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_set.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fnv_1.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/format_spec.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/forward_list.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/frame_check_sequence.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fsm.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/function.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/functional.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/gamma.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/generic_pool.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/hash.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/histogram.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ihash.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/imemory_block_allocator.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/indirect_vector.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/initializer_list.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/instance_count.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/integral_limits.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_forward_list.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_links.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_list.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_queue.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_stack.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/invert.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/io_port.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ipool.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ireference_counted_message_pool.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/iterator.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/jenkins.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/largest.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/limiter.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/limits.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/list.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/log.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/macros.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/map.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/math_constants.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mean.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mem_cast.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/memory.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/memory_model.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_bus.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_packet.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_router.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_router_registry.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_timer.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_timer_atomic.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_types.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_array.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_range.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_span.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_vector.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multimap.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multiset.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/murmur3.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mutex.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/negative.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/nth_type.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/null_type.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/nullptr.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/numeric.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/observer.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/optional.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/overload.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/packet.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/parameter_pack.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/parameter_type.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/pearson.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/permutations.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/placement_new.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/platform.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/pool.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/power.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/priority_queue.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/quantize.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_lockable.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_mpmc_mutex.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_atomic.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_isr.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_locked.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/radix.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/random.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ratio.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_message.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_message_pool.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_object.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_map.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_multimap.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_multiset.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_set.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/rescale.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/rms.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/scaled_rounding.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/scheduler.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/set.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/shared_message.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/singleton.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/smallest.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/span.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/sqrt.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/stack.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/standard_deviation.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/state_chart.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/static_assert.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_stream.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_utilities.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_view.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/successor.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/task.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/threshold.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/timer.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_string.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_u16string.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_u32string.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_wstring.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_def.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_lookup.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_select.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_traits.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16format_spec.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16string.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16string_stream.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32format_spec.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32string.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32string_stream.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unaligned_type.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_map.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_multimap.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_multiset.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_set.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/user_type.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/utility.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variance.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_legacy.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_old.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_pool.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_variadic.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/vector.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/version.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/visitor.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wformat_spec.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wstring.h.t.cpp \
../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wstring_stream.h.t.cpp 

OBJS += \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/absolute.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/algorithm.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/alignment.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array_view.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array_wrapper.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/atomic.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_format_spec.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_string.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_string_stream.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/binary.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bip_buffer_spsc_atomic.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bit.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bit_stream.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bitset.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bloom_filter.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bresenham_line.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/buffer_descriptors.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/byte.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/byte_stream.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_service.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_timer.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_timer_atomic.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/char_traits.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/checksum.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/circular_buffer.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/combinations.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/compare.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/constant.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/container.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/correlation.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/covariance.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_a.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_arc.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_aug_ccitt.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_buypass.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_ccitt.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_cdma2000.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dds110.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dectr.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dectx.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dnp.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_en13757.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_genibus.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_kermit.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_maxim.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_mcrf4xx.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_modbus.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_profibus.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_riello.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_t10dif.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_teledisk.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_tms37157.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_usb.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_x25.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_xmodem.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_bzip2.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_c.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_d.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_jamcrc.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_mpeg2.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_posix.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_q.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_xfer.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc64_ecma.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_ccitt.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_cdma2000.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_darc.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_dvbs2.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_ebu.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_icode.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_itu.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_maxim.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_rohc.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_wcdma.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/cumulative_moving_average.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/cyclic_value.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/debounce.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/debug_count.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate_cpp03.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate_service.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/deque.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/endianness.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/enum_type.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/error_handler.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/exception.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/factorial.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fibonacci.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/file_error_numbers.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fixed_iterator.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fixed_sized_memory_block_allocator.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flags.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_map.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_multimap.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_multiset.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_set.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fnv_1.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/format_spec.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/forward_list.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/frame_check_sequence.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fsm.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/function.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/functional.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/gamma.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/generic_pool.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/hash.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/histogram.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ihash.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/imemory_block_allocator.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/indirect_vector.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/initializer_list.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/instance_count.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/integral_limits.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_forward_list.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_links.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_list.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_queue.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_stack.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/invert.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/io_port.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ipool.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ireference_counted_message_pool.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/iterator.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/jenkins.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/largest.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/limiter.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/limits.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/list.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/log.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/macros.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/map.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/math_constants.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mean.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mem_cast.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/memory.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/memory_model.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_bus.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_packet.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_router.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_router_registry.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_timer.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_timer_atomic.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_types.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_array.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_range.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_span.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_vector.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multimap.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multiset.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/murmur3.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mutex.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/negative.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/nth_type.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/null_type.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/nullptr.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/numeric.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/observer.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/optional.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/overload.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/packet.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/parameter_pack.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/parameter_type.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/pearson.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/permutations.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/placement_new.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/platform.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/pool.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/power.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/priority_queue.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/quantize.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_lockable.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_mpmc_mutex.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_atomic.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_isr.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_locked.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/radix.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/random.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ratio.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_message.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_message_pool.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_object.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_map.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_multimap.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_multiset.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_set.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/rescale.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/rms.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/scaled_rounding.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/scheduler.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/set.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/shared_message.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/singleton.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/smallest.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/span.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/sqrt.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/stack.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/standard_deviation.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/state_chart.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/static_assert.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_stream.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_utilities.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_view.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/successor.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/task.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/threshold.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/timer.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_string.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_u16string.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_u32string.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_wstring.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_def.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_lookup.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_select.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_traits.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16format_spec.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16string.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16string_stream.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32format_spec.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32string.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32string_stream.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unaligned_type.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_map.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_multimap.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_multiset.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_set.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/user_type.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/utility.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variance.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_legacy.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_old.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_pool.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_variadic.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/vector.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/version.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/visitor.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wformat_spec.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wstring.h.t.o \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wstring_stream.h.t.o 

CPP_DEPS += \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/absolute.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/algorithm.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/alignment.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array_view.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array_wrapper.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/atomic.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_format_spec.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_string.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_string_stream.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/binary.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bip_buffer_spsc_atomic.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bit.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bit_stream.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bitset.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bloom_filter.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bresenham_line.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/buffer_descriptors.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/byte.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/byte_stream.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_service.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_timer.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_timer_atomic.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/char_traits.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/checksum.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/circular_buffer.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/combinations.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/compare.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/constant.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/container.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/correlation.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/covariance.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_a.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_arc.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_aug_ccitt.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_buypass.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_ccitt.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_cdma2000.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dds110.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dectr.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dectx.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dnp.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_en13757.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_genibus.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_kermit.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_maxim.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_mcrf4xx.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_modbus.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_profibus.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_riello.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_t10dif.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_teledisk.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_tms37157.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_usb.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_x25.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_xmodem.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_bzip2.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_c.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_d.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_jamcrc.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_mpeg2.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_posix.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_q.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_xfer.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc64_ecma.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_ccitt.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_cdma2000.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_darc.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_dvbs2.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_ebu.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_icode.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_itu.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_maxim.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_rohc.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_wcdma.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/cumulative_moving_average.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/cyclic_value.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/debounce.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/debug_count.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate_cpp03.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate_service.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/deque.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/endianness.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/enum_type.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/error_handler.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/exception.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/factorial.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fibonacci.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/file_error_numbers.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fixed_iterator.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fixed_sized_memory_block_allocator.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flags.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_map.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_multimap.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_multiset.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_set.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fnv_1.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/format_spec.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/forward_list.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/frame_check_sequence.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fsm.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/function.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/functional.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/gamma.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/generic_pool.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/hash.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/histogram.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ihash.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/imemory_block_allocator.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/indirect_vector.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/initializer_list.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/instance_count.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/integral_limits.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_forward_list.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_links.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_list.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_queue.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_stack.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/invert.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/io_port.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ipool.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ireference_counted_message_pool.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/iterator.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/jenkins.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/largest.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/limiter.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/limits.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/list.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/log.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/macros.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/map.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/math_constants.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mean.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mem_cast.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/memory.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/memory_model.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_bus.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_packet.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_router.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_router_registry.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_timer.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_timer_atomic.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_types.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_array.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_range.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_span.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_vector.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multimap.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multiset.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/murmur3.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mutex.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/negative.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/nth_type.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/null_type.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/nullptr.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/numeric.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/observer.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/optional.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/overload.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/packet.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/parameter_pack.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/parameter_type.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/pearson.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/permutations.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/placement_new.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/platform.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/pool.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/power.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/priority_queue.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/quantize.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_lockable.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_mpmc_mutex.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_atomic.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_isr.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_locked.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/radix.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/random.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ratio.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_message.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_message_pool.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_object.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_map.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_multimap.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_multiset.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_set.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/rescale.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/rms.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/scaled_rounding.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/scheduler.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/set.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/shared_message.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/singleton.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/smallest.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/span.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/sqrt.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/stack.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/standard_deviation.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/state_chart.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/static_assert.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_stream.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_utilities.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_view.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/successor.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/task.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/threshold.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/timer.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_string.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_u16string.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_u32string.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_wstring.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_def.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_lookup.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_select.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_traits.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16format_spec.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16string.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16string_stream.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32format_spec.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32string.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32string_stream.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unaligned_type.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_map.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_multimap.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_multiset.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_set.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/user_type.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/utility.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variance.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_legacy.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_old.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_pool.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_variadic.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/vector.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/version.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/visitor.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wformat_spec.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wstring.h.t.d \
./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wstring_stream.h.t.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/%.o: ../Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/%.cpp Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m0 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F072xB -DETL_CALLBACK_TIMER_USE_ATOMIC_LOCK -c -I../Core/Inc -I../Drivers/STM32F0xx_HAL_Driver/Inc -I../Drivers/STM32F0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F0xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I"C:/Users/georg/STM32CubeIDE/SolarGators/OpenTelemetry/Drivers/SolarGatorsBSP_STM/DataModules/inc" -I"C:/Users/georg/STM32CubeIDE/SolarGators/OpenTelemetry/Drivers/SolarGatorsBSP_STM/Drivers/inc" -I"C:/Users/georg/STM32CubeIDE/SolarGators/OpenTelemetry/Drivers/SolarGatorsBSP_STM/etl/include" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Drivers-2f-SolarGatorsBSP_STM-2f-etl-2f-test-2f-sanity-2d-check

clean-Drivers-2f-SolarGatorsBSP_STM-2f-etl-2f-test-2f-sanity-2d-check:
	-$(RM) ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/absolute.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/absolute.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/algorithm.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/algorithm.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/alignment.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/alignment.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array_view.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array_view.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array_wrapper.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/array_wrapper.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/atomic.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/atomic.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_format_spec.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_format_spec.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_string.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_string.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_string_stream.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/basic_string_stream.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/binary.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/binary.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bip_buffer_spsc_atomic.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bip_buffer_spsc_atomic.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bit.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bit.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bit_stream.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bit_stream.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bitset.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bitset.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bloom_filter.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bloom_filter.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bresenham_line.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/bresenham_line.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/buffer_descriptors.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/buffer_descriptors.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/byte.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/byte.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/byte_stream.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/byte_stream.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_service.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_service.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_timer.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_timer.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_timer_atomic.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/callback_timer_atomic.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/char_traits.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/char_traits.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/checksum.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/checksum.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/circular_buffer.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/circular_buffer.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/combinations.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/combinations.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/compare.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/compare.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/constant.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/constant.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/container.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/container.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/correlation.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/correlation.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/covariance.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/covariance.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_a.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_a.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_arc.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_arc.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_aug_ccitt.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_aug_ccitt.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_buypass.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_buypass.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_ccitt.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_ccitt.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_cdma2000.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_cdma2000.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dds110.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dds110.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dectr.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dectr.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dectx.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dectx.h.t.o
	-$(RM) ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dnp.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_dnp.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_en13757.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_en13757.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_genibus.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_genibus.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_kermit.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_kermit.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_maxim.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_maxim.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_mcrf4xx.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_mcrf4xx.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_modbus.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_modbus.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_profibus.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_profibus.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_riello.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_riello.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_t10dif.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_t10dif.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_teledisk.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_teledisk.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_tms37157.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_tms37157.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_usb.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_usb.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_x25.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_x25.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_xmodem.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc16_xmodem.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_bzip2.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_bzip2.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_c.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_c.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_d.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_d.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_jamcrc.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_jamcrc.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_mpeg2.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_mpeg2.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_posix.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_posix.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_q.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_q.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_xfer.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc32_xfer.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc64_ecma.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc64_ecma.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_ccitt.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_ccitt.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_cdma2000.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_cdma2000.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_darc.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_darc.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_dvbs2.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_dvbs2.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_ebu.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_ebu.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_icode.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_icode.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_itu.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_itu.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_maxim.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_maxim.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_rohc.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_rohc.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_wcdma.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/crc8_wcdma.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/cumulative_moving_average.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/cumulative_moving_average.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/cyclic_value.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/cyclic_value.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/debounce.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/debounce.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/debug_count.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/debug_count.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate_cpp03.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate_cpp03.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate_service.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/delegate_service.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/deque.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/deque.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/endianness.h.t.d
	-$(RM) ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/endianness.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/enum_type.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/enum_type.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/error_handler.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/error_handler.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/exception.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/exception.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/factorial.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/factorial.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fibonacci.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fibonacci.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/file_error_numbers.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/file_error_numbers.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fixed_iterator.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fixed_iterator.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fixed_sized_memory_block_allocator.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fixed_sized_memory_block_allocator.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flags.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flags.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_map.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_map.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_multimap.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_multimap.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_multiset.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_multiset.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_set.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/flat_set.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fnv_1.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fnv_1.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/format_spec.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/format_spec.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/forward_list.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/forward_list.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/frame_check_sequence.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/frame_check_sequence.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fsm.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/fsm.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/function.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/function.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/functional.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/functional.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/gamma.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/gamma.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/generic_pool.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/generic_pool.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/hash.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/hash.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/histogram.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/histogram.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ihash.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ihash.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/imemory_block_allocator.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/imemory_block_allocator.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/indirect_vector.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/indirect_vector.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/initializer_list.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/initializer_list.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/instance_count.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/instance_count.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/integral_limits.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/integral_limits.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_forward_list.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_forward_list.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_links.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_links.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_list.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_list.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_queue.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_queue.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_stack.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/intrusive_stack.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/invert.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/invert.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/io_port.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/io_port.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ipool.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ipool.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ireference_counted_message_pool.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ireference_counted_message_pool.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/iterator.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/iterator.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/jenkins.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/jenkins.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/largest.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/largest.h.t.o
	-$(RM) ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/limiter.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/limiter.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/limits.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/limits.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/list.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/list.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/log.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/log.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/macros.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/macros.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/map.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/map.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/math_constants.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/math_constants.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mean.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mean.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mem_cast.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mem_cast.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/memory.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/memory.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/memory_model.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/memory_model.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_bus.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_bus.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_packet.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_packet.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_router.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_router.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_router_registry.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_router_registry.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_timer.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_timer.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_timer_atomic.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_timer_atomic.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_types.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/message_types.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_array.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_array.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_range.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_range.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_span.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_span.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_vector.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multi_vector.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multimap.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multimap.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multiset.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/multiset.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/murmur3.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/murmur3.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mutex.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/mutex.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/negative.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/negative.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/nth_type.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/nth_type.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/null_type.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/null_type.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/nullptr.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/nullptr.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/numeric.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/numeric.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/observer.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/observer.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/optional.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/optional.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/overload.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/overload.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/packet.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/packet.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/parameter_pack.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/parameter_pack.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/parameter_type.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/parameter_type.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/pearson.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/pearson.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/permutations.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/permutations.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/placement_new.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/placement_new.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/platform.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/platform.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/pool.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/pool.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/power.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/power.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/priority_queue.h.t.d
	-$(RM) ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/priority_queue.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/quantize.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/quantize.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_lockable.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_lockable.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_mpmc_mutex.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_mpmc_mutex.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_atomic.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_atomic.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_isr.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_isr.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_locked.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/queue_spsc_locked.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/radix.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/radix.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/random.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/random.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ratio.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/ratio.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_message.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_message.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_message_pool.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_message_pool.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_object.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_counted_object.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_map.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_map.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_multimap.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_multimap.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_multiset.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_multiset.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_set.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/reference_flat_set.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/rescale.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/rescale.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/rms.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/rms.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/scaled_rounding.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/scaled_rounding.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/scheduler.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/scheduler.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/set.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/set.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/shared_message.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/shared_message.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/singleton.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/singleton.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/smallest.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/smallest.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/span.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/span.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/sqrt.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/sqrt.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/stack.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/stack.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/standard_deviation.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/standard_deviation.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/state_chart.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/state_chart.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/static_assert.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/static_assert.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_stream.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_stream.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_utilities.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_utilities.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_view.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/string_view.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/successor.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/successor.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/task.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/task.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/threshold.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/threshold.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/timer.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/timer.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_string.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_string.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_u16string.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_u16string.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_u32string.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_u32string.h.t.o
	-$(RM) ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_wstring.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/to_wstring.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_def.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_def.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_lookup.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_lookup.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_select.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_select.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_traits.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/type_traits.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16format_spec.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16format_spec.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16string.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16string.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16string_stream.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u16string_stream.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32format_spec.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32format_spec.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32string.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32string.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32string_stream.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/u32string_stream.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unaligned_type.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unaligned_type.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_map.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_map.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_multimap.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_multimap.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_multiset.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_multiset.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_set.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/unordered_set.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/user_type.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/user_type.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/utility.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/utility.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variance.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variance.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_legacy.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_legacy.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_old.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_old.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_pool.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_pool.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_variadic.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/variant_variadic.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/vector.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/vector.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/version.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/version.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/visitor.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/visitor.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wformat_spec.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wformat_spec.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wstring.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wstring.h.t.o ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wstring_stream.h.t.d ./Drivers/SolarGatorsBSP_STM/etl/test/sanity-check/wstring_stream.h.t.o

.PHONY: clean-Drivers-2f-SolarGatorsBSP_STM-2f-etl-2f-test-2f-sanity-2d-check

