name: Integration Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: Solar-Gators/STM32-Infrastructure@main
        with:
          project-path: '/github/workspace/'
          project-target: 'OpenTelemetry'

      - uses: actions/upload-artifact@v3
        with:
          name: 'Release Binary'
          path: ./Release/*.elf
